const data = {
    products:[
        {
            _id: '1',
            name: 'Sueter Adidas',
            category: 'Sueter',
            image: '/images/product-1.jpeg',
            price: '120.000',
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 25,
            countInStock: 10,
            description: 'High Quality Product',
        },
        {
            _id: '2',
            name: 'Sueter Adidas',
            category: 'Sueter',
            image: '/images/product-2.jpeg',
            price: '140.000',
            brand: 'Adidas',
            rating: 4.8,
            numReviews: 10,
            countInStock: 6,
            description: 'High Quality Product',
        },
        {
            _id: '3',
            name: 'Sueter Adidas',
            category: 'Sueter',                                 
            image: '/images/product-3.jpeg',
            price: '100.000',
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 14,
            countInStock: 0,
            description: 'High Quality Product',
        },
        {
            _id: '4',
            name: 'Sueter Adidas',
            category: 'Sueter',                                 
            image: '/images/product-4.jpeg',
            price: '180.000',
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 23,
            countInStock: 5,
            description: 'High Quality Product',
        },
        {
            _id: '5',
            name: 'Sueter Adidas',
            category: 'Sueter',                                 
            image: '/images/product-5.jpeg',
            price: '90.000',
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 18,
            countInStock: 0,
            description: 'High Quality Product',
        },
        {
            _id: '6',
            name: 'Sueter Adidas',
            category: 'Sueter',                                 
            image: '/images/product-6.jpeg',
            price: '190.000',
            brand: 'Adidas',
            rating: 4.9,
            numReviews: 24,
            countInStock: 1,
            description: 'High Quality Product',
        },
    ],
}; 
export default data;