const data = {
    products:[
        {
            _id: '1',
            name: 'Sueter Adidas',
            category: 'Sueter',
            image: '/images/product-1.jpeg',
            price: 120,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 25,
            countInStock: 10,
            description: 'High Quality Product',
        },
        {
            _id: '2',
            name: 'Sueter Adidas',
            category: 'Sueter',
            image: '/images/product-2.jpeg',
            price: 140,
            brand: 'Adidas',
            rating: 4.8,
            numReviews: 10,
            countInStock: 6,
            description: 'High Quality Product',
        },
        {
            _id: '3',
            name: 'Sueter Adidas',
            category: 'Sueter',                                 
            image: '/images/product-3.jpeg',
            price: 100,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 14,
            countInStock: 0,
            description: 'High Quality Product',
        },
    ],
}; 
export default data;