const data = {
    products:[
        {
            _id: '1',
            name: 'Sueter Adidas',
            category: 'Sueter',
            image: '/images/product-1.jpeg',
            price: 120,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Sueter Adidas',
            category: 'Sueter',
            image: '/images/product-2.jpeg',
            price: 140,
            brand: 'Adidas',
            rating: 4.8,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Sueter Adidas',
            category: 'Sueter',                                 
            image: '/images/product-3.jpeg',
            price: 100,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
}; 